- name: Common roles for all hosts
  hosts: all
  roles:
    - role: logcheck
      tags: [logcheck]
    - role: unbound
      tags: [unbound]

- name: DNS contents server for samba.gr.jp
  hosts: dns-contents
  roles:
    - role: powerdns/authoritative
      tags: [pdns, pdns-auth]

