- name: "Debian packages"
  apt:
    name: "{{item}}"
    state: present
    update_cache: false
  with_items: pdns-server
  become: true

- name: "/etc/powerdns/pdns.conf"
  copy:
    src=pdns.conf
    dest=/etc/powerdns/pdns.conf
    mode=0640
    owner=root
    group=pdns
    backup=true
  become: true
  notify: pdns restart

- name: "/etc/powerdns/pdns.d/bind.conf"
  copy:
    src=bind.conf
    dest=/etc/powerdns/pdns.d/bind.conf
    mode=0640
    owner=root
    group=pdns
    backup=true
  become: true
  notify: pdns restart

- name: "/etc/powerdns/named.conf"
  copy:
    src=named.conf
    dest=/etc/powerdns/named.conf
    mode=0640
    owner=root
    group=pdns
    backup=true
  become: true
  notify: pdns restart

- name: "/etc/powerdns/samba.gr.jp.zone"
  copy:
    src=samba.gr.jp.zone
    dest=/etc/powerdns/samba.gr.jp.zone
    mode=0640
    owner=root
    group=pdns
    backup=true
  become: true
  notify: pdns reload-zones

- name: "pdns service"
  service:
    name=pdns
    state=started
    enabled=true
  become: true
