- name: "Debian packages"
  apt:
    name: "{{item}}"
    state: latest
    update_cache: true
  with_items:
    - logcheck
    - logcheck-database
  become: true

- name: "/etc/logcheck/ignore.d.server/local"
  copy:
    src=ignore.d.server/local
    dest=/etc/logcheck/ignore.d.server/local
    mode=0640
    owner=root
    group=logcheck
  become: true

